### PR TITLE
Implement ShortRecyclerView

### LINKED ISSUE #1: Add Recycler View to simplify usage
ShortRoid aims to make android development easy by simplifying android codes by creating easy to use wrapper around some boilerplate code. 
Main objective is to do a job only in few lines

Already ShortRoid has three classes:
1. ShortRoidDB - Use SQlLite DB in few lines of code
2. ShortRoidPreference - Shared Preferences in just 2 lines
3 ShortAnimation - Animation of views in one line

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
Fixes #1

### CODE REVIEW

**Review by prashant2018 — CHANGES_REQUESTED** [review]
Hi,
Your implementation is really good. But how will the user apply the adapter to the recyclerview. I think it would be better if you add the adapter functionality. We are aiming to implement custom adapters using recyclerview easily to populate custom data.

**Comment by SubhrajyotiSen** [comment]
Hey, adapters can be set normally like

`shortRecyclerView.setAdapter(mAdapter);`

**Comment by prashant2018** [comment]
@SubhrajyotiSen I know what you are saying but we are looking for a short implementation of a RecyclerView,Adapter<ViewHolder> too in addition to your work, why not use interface for overriding methods of RecyclerView.Adapter

**Comment by SubhrajyotiSen** [comment]
I got it know. Will try the Adapter implementation tomorrow

**Comment by prashant2018** [comment]
@SubhrajyotiSen  thats great, thanks

**Comment by SubhrajyotiSen** [comment]
@prashant2018 Can you please give me some pseudocode of what you are expecting?

**Comment by mohitbadwal** [comment]
@SubhrajyotiSen The basic idea  is to decrease the effort needed to implement a RecyclerView with a Custom Adapter.
You might use an interface class to override methods like onBindViewHolder() etc which are a part of the RecyclerView.Adapter class and this might help decrease code.

**Pull request merged**
